### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by jnystad** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#108]
Hi guys,

When is a new release due? The last was almost two years ago, and some important fixes have been merged to develop since then.

Thanks!

**Comment by peetw** [comment]
I would be particularly interested in the fix for geometries with Z values, as implemented in #76.

@airbreather @FObermaier is there a plan/roadmap for when a new release might be available?

**Comment by FObermaier** [comment]
@peetw, I'm working on it, some cleanup still needs to be done.

**Comment by FObermaier** [comment]
@airbreather, I think this is in a state where we can issue a new release, what do you think?

**Comment by airbreather** [comment]
Yes, I'm fine with doing a release now.

**Comment by airbreather** [comment]
I've gone ahead and updated some pages on the wiki to replace the examples of using the obsolete extension methods with their not-obsolete counterparts, and I've also made some updates to document using this together with a couple of things that have been added to ASP.NET Core since 3.1 (namely, `WebApplicationBuilder` and minimal APIs)
