### ISSUE TITLE
Can't modify STJ's Attribute Table

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#117]
I'm getting the following error when trying to add a field to an `AttributeTable` after deserializing a feature using the STJ 
`NotSupportedException: Modifying this attribute table is not supported.`
Is this a missing feature?
Here's the failing test if that helps:
```cs
        [TestMethod]
        public void AddAttributeFailure()
        {
            string str = @"
                 {
                    ""type"": ""Feature"",
                    ""geometry"": {
                        ""type"": ""Point"",
                        ""coordinates"" : [
                            35.0666687,
                            32.5499986
                        ]
                    },
                    ""properties"": {
                        ""accuracy"": ""minutes""
                    },
                    ""poiId"": ""OSM_node_278470424"",
                    ""poiGeolocation"": {
                        ""lat"": 32.5499986,
                        ""lon"": 35.0666687
                    },
                    ""poiAlt"": 172.0123568908041
                }";
            var factory = new GeoJsonConverterFactory();
            var indentedOptions = new JsonSerializerOptions
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                WriteIndented = true
            };
            indentedOptions.Converters.Add(factory);

            var f = JsonSerializer.Deserialize<IFeature>(str, indentedOptions);
            Assert.IsNotNull(f);
            f.Attributes.Add("test", "test");
            Assert.IsTrue(f.Attributes.Exists("test"));
        }
```

**Comment by airbreather** [comment]
4STJ attributes tables are read-only, as System.Text.Json didn't have support for writable DOM objects until version 6.

Now that it has this functionality, we could look into bumping up our minimum supported version of that dependency.

**Comment by HarelM** [comment]
I honestly can't find documentation about how to edit/modify/clone-update a `JsonElement` which is the underlying data structure below JsonElementAttributeTable.
Having said that, I'm not sure I fully understand the decision to use that as an underlaying data structure.
Selecting that basically breaks the API and `IAttributeTable` interface as there are "unimplemented" methods.
I'll be happy to help push this forward as this is currently a blocker for me to finish the STJ migration.
Yes, I know, I can make a "convert to regular `AttributeTable`" and then use that, but it feels a bit awkward...

**Comment by airbreather** [comment]
> I honestly can't find documentation about how to edit/modify/clone-update a `JsonElement` which is the underlying data structure below JsonElementAttributeTable.

I'm working on it right now.  In case I disappear before finishing it, the important part is: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonobject.create

>  Selecting that basically breaks the API and `IAttributeTable` interface as there are "unimplemented" methods.

Sort-of... I'd say that it's a bit more like `ICollection<T>` when [`IsReadOnly`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.isreadonly) is `false`.  I know that we don't have an `IsReadOnly` that you can use to check this in advance, so it's admittedly worse here than in `ICollection<T>`.

> Yes, I know, I can make a "convert to regular `AttributeTable`" and then use that

That's the reasoning behind the decision.  The intentional design limitations of System.Text.Json prevent us from deserializing an entire object graph of any arbitrary top-level type ahead-of-time using **only** information that's present in the GeoJSON object, so we had to look at other ways of representing the nested structure.

There are a number of viable options here, each with their own pros and cons.  The approach that we took allows the system to do the minimum amount of work that's necessary to support reading the values, which I imagine is all that the overwhelming majority of consumers need from it.  And because it throws `NotSupportedException` when you try to write anything, we can always add that support later without breaking anything that was working before.

**Comment by HarelM** [comment]
So I'm guessing you are planning to switch from `JsonElement` to `JsonObject`, right?
I'm having a hard time opening and running this project in Rider for some reason, not sure why... :-/
In any case, if you have a pre-release nuget package for STJ you can share that allow modifying the attribute table without knowing the underlaying implementation let me know and I'll be happy to test it.
I'm guessing that adding support just for that shouldn't be too difficult...

**Comment by airbreather** [comment]
> So I'm guessing you are planning to switch from `JsonElement` to `JsonObject`, right?

As nice as that sounds, it's nothing quite so simple, I'm afraid...

In nearly every case, I expect the overhead involved in creating a writable object is going to go to waste, so I don't want to do that eagerly.  The whole reason why `System.Text.Json` exists (as I understand it) is because `Newtonsoft.Json`'s design forces onto every consumer, in order to support features that a majority of consumers don't need a majority of the time.

Throughout my involvement in the design and development of NTS.IO.GeoJSON4STJ, I've made it a personal goal to stay true to that design philosophy.  That is consistent with the factors that I feel are most likely to motivate people to choose this library over NTS.IO.GeoJSON.

So to that end, my overall plan is as follows (this is subject to change if needed, of course!):
1. For consumers who **only ever** need to **read** the attributes, everything will remain exactly the same as it's always been, and none of the rest of this list will apply to them.
    - *Technically, they will likely have to live with the table object itself taking up an additional pointer-sized object reference and deal with some trivially more complicated logic at the start of most methods... all within the same ballpark as the overhead of `JsonElement` itself, though.*
1. The first time someone **modifies** an attributes table, we will copy the `JsonElement` to a `JsonObject` that we hold onto in order to support those modifications.  Once that `JsonObject` exists, all the other methods will use it instead of the `JsonElement` that it was created from.
1. Further modifications will edit that same `JsonObject`.
1. After making any modifications, trying to externally access the `RootElement` property will do... something (haven't gotten this far yet in my plan).  Reasonable-sounding options I can think of while typing this up are:
    - Return the original value that it was created from.
    - Return a value that represents the current state  No further modifications will be propagated to this value.
    - (I don't think it's possible to return a value that will also observe further modifications.  I haven't checked, though, so this bullet point is here to cover that.)
    - Throw an exception because it's unclear what alternative semantics make more sense, and this probably isn't all that important anyway, so defer the decision point until someone opens another issue like this one.

This is probably one of the more complicated ways to solve this problem... what I would have **liked** to have had is an `IAttributesTable.IsReadOnly` flag on that I could have pointed you to, along with a simple `.ToWritable()` extension method (or similar) that you could use to opt-in to all this overhead.  But adding members to interfaces is always a breaking change (in .NET Standard 2.0, anyway...), and so if `IsReadOnly` wasn't there before, it's problematic to add it later.

>  In any case, if you have a pre-release nuget package for STJ you can share that allow modifying the attribute table without knowing the underlaying implementation let me know and I'll be happy to test it.
>  I'm guessing that adding support just for that shouldn't be too difficult...

I think I don't quite follow your proposal  The only reasonable cheap alternative I can think of immediately is to add some constructor overload(s) to `AttributesTable` that let you initialize it using the values from some other `IAttributesTable` object.  Is that something like what you're suggesting?

**Comment by HarelM** [comment]
The last part assumes this isn't too difficult too implement (allowing modification to attribute table), so if you implement it and want me to test it I'll be happy to, using a pre-release nuget package I guess...

**Comment by airbreather** [comment]
The problem I'm running into when trying to implement the idea I mentioned in https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/issues/117#issuecomment-1412807595 is that a JSON object that's nested inside of a `JsonElementAttributesTable` is exposed as an inner `JsonElementAttributesTable`.  If we're going to allow modifications to this type, then modifications to an instance should be reflected in all containing instances.

The more I dug into this, the more problems I found that `System.Text.Json.Nodes` just flat-out solves.  So my new plan is to create a separate `IAttributesTable` implementation that's backed by a `JsonObject`, and add an opt-in flag to `GeoJsonConverterFactory` that tells us to use it when deserializing features.

**Comment by HarelM** [comment]
Cool! Thanks for looking into it!!
Let me know when you have a pre-release Nuget package I can take for a spin :-)

**Comment by HarelM** [comment]
This looks like it is working as expected. Thanks!!
We all make mistakes :-) as long as we can correct them it fine. Good thing I chose to code and not to do brain surgery. :-P

**Comment by HarelM** [comment]
Let me know when a new official version is available so I can remove the temporary myget source.
THANKS!

**Comment by airbreather** [comment]
>Let me know when a new official version is available so I can remove the temporary myget source.
>THANKS!

@HarelM this is the notification that you requested.

**Comment by HarelM** [comment]
Cool! THANKS! Keep up the good work!

**Comment by x0rld** [comment]
Hi
I tried to modify an AttributeTable and I have a this exception `NotSupportedException: Modifying this attribute table is not supported`
my code 
```cs
        var serializerOptions = new JsonSerializerOptions();
        serializerOptions.Converters.Add(new NetTopologySuite.IO.Converters.GeoJsonConverterFactory());
        var featureCollection = await JsonSerializer.DeserializeAsync<FeatureCollection>(fileStream, serializerOptions);
        var collection = new FeatureCollection();
        foreach (var feature in featureCollection)
        {
            var attributes = feature.Attributes;
            var consumption = Helpers.ComputeArea(feature.Geometry) *
                                   (feature.Attributes.Exists("levels")
                                       ? Convert.ToDouble(feature.Attributes["levels"] ?? 1)
                                       : 1) *
                                   60;
            attributes["consumption"] = consumption;
            collection.Add(feature);
        }
```
I did something wrong ?
