### ISSUE TITLE
`POLYGON Empty` etc

### ISSUE THREAD

**Issue by juliusfriedman** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#54]
Consider: 

```sql
SELECT geography::STGeomFromText('POLYGON EMPTY', 4326)
```

Consider this code:

```c#
using var (testOut= File.Create(".test.geojson"))
			{
				using (var utf8JsonWriter = new System.Text.Json.Utf8JsonWriter(testOut))
				{
					System.Text.Json.JsonSerializer.Serialize(utf8JsonWriter, new FeatureCollection() { new Feature(new NetTopologySuite.IO.WKTReader().Read("POLYGON EMPTY"), new AttributesTable() { { "test", "1" } }) }, JsonSerializerOptions);
				}
			}
```

The Polygon is not valid so an exception is thrown and the program crashes...

Seems like the problem comes from something in the base library.

See: https://github.com/NetTopologySuite/NetTopologySuite/issues/422

I think it's also important to have sentinels for `Geometry.Empty` which would make working with `null` a lot nicer.

**Comment by juliusfriedman** [comment]
cc @airbreather @FObermaier

**Comment by airbreather** [comment]
#55

**Comment by juliusfriedman** [comment]
Thank you, could you also address the issue where the Polygons are reversed by the serializer? I can't seem to find that issue anymore...

Since Reverse returns a new geometry every time there is no reason to force the user to reverse their geometry again after serialization simply use the reversed one in serialization and then keep the original the way it was!.

Thank you!

**Comment by airbreather** [comment]
> Thank you, could you also address the issue where the Polygons are reversed by the serializer? I can't seem to find that issue anymore...
> 
> Since Reverse returns a new geometry every time there is no reason to force the user to reverse their geometry again after serialization simply use the reversed one in serialization and then keep the original the way it was!.

If you're talking about #52, can you please elaborate on the specific issue that arises from 4STJ following the spec?

`Deserialize(Serialize(original)).EqualsExact(original)` is going to be `false`, but the object from the round-trip still has the exact same semantics as the original (i.e., `Deserialize(Serialize(original)).EqualsTopologically(original)` is `true`).

> Also, any change for the Sentinels? Geometry.Empty, which can then be virtual and overridden for Polygon.Empty etc

If you're recommending that we expose something like a `Geometry.Empty` property, perhaps so that you can get an empty geometry instance without having to allocate a new one every time, a major problem with that concept is the `Geometry.Factory` property.
- So something like `UnaryUnionOp.Union(new[] { geom1, geom2, geom3 })` may give you a different result if `geom1` came from `Geometry.Empty` vs. if it came from `someOtherFactory.CreatePolygon()`.

The recommended way to get an empty `Polygon` is to use [`GeometryFactory.CreatePolygon()`](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.GeometryFactory.html#NetTopologySuite_Geometries_GeometryFactory_CreatePolygon).  If you need to cache the result, then feel free to do so as appropriate for your own use case.

**Comment by juliusfriedman** [comment]
Happy enough to see this fixed, will take my issues to the other thread for the other thing.

Thank you for your time!
