### ISSUE TITLE
Simpler JSON schema

### ISSUE THREAD

**Issue by verdie-g** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#83]
Hello, I found the JSON objects akward to use in a web application. 

# Problem

The typescript definition of a point looks like this
```typescript
interface Point {
  type: 'Point';
  coordinates: [number, number];
}
```
When you deserialize the response of a REST API, you already know its schema so you don't expect the name of the type to be included so the field `type` is always going to be ignored and accessing the coordinate is verbose (`myPoint.coordinates[0]`).

This first point, wouldn't bother if the definition of a `Point` was consistent. You would expect that the schema of a `MultiPoint` be
```typescript
interface MultiPoint {
  type: 'MultiPoint';
  coordinates: Point[];
```
but actually it is
```typescript
interface MultiPoint {
  type: 'MultiPoint';
  coordinates: [[number; number]];
}
```
which I think is a good idea otherwise the JSON of a `MultiPoint` would be bloated with `"type": "Point"` but now if I want to make a method accepting a point as a parameter I'm not sure if I should use `Point` or `[number; number]`.

# Suggested solution

What do you think of a new `JsonConverter` called `SimpleGeoJsonConverterFactory` that would serialize:
- a `Point` as a `[number; number]`
- `MultiPoint`, `LineString`, `Polygon`, `LinearRing` as a `[[number; number]]`
- `MultiLineString`, `MultiPolygon` as `[[[number; number]]]`
- `GeometryCollection` as `[{ type: 'MultiPoint' | 'LineString' | 'Polygon' | 'LinearRing' | ..., coordinates: [number; number] | [[number; number]] | [[[number; number]]] }]`

I could make the implementation if you are okay with this.

**Comment by airbreather** [comment]
I agree that the format is often redundant (at best) for many practical uses, and out-of-band metadata information can usually make the results **much** more compact than what we use here.

However, the goal of this project is to implement a strict subset of JSON called [GeoJSON](https://geojson.org/), which is a standard that is used throughout the industry for transferring spatial objects across application boundaries, potentially even between applications written in wildly different languages.

Therefore, it would be very difficult to accept a proposal that drastically alters the input or output formats, especially in ways that are incompatible with GeoJSON.

**Comment by airbreather** [comment]
> I found the JSON objects akward to use in a web application.

In fact, what language are you working in?  That looks kinda like TypeScript... if so, try [`@types/geojson`](https://www.npmjs.com/package/@types/geojson)?

**Comment by DGuidi** [comment]
probably worth mention that there is a not-completed Topojson  implementation that maybe can be helpful in those cases, just because it's a standard and it's a lot more compact. 
Unfortunately, the writer right now it's not implemented...

**Comment by airbreather** [comment]
> I found the JSON objects akward to use in a web application.
>
> The typescript definition of a point looks like this

Have you looked into using [`@types/geojson`](https://www.npmjs.com/package/@types/geojson)?  That should include all the type declarations for you.

**Comment by verdie-g** [comment]
Thanks for the quick answer.

> the goal of this project is to implement a strict subset of JSON called GeoJSON

Of course, I should have checked that.

> Have you looked into using @types/geojson?

Thanks, that will definitely help.

Still, I would prefer that my REST API return a compact object. I don't think I will loose much from deviating from the geojson standard. Do you think it would make sense to add a more compact JSON representation of the geometries in this project? I could make my own project but most of the code will be very similar to this project.

> there is a not-completed Topojson implementation that maybe can be helpful in those cases
Is Topojson more compact. Looking quickly at https://github.com/topojson/topojson-specification#11-examples it seems like it's not the case.

**Comment by airbreather** [comment]
> Still, I would prefer that my REST API return a compact object. I don't think I will loose much from deviating from the geojson standard. Do you think it would make sense to add a more compact JSON representation of the geometries in this project?

I'm going to respond to this from the perspective of what I perceive to be the overwhelmingly most common use cases for this kind of data.  If you think that your use case is more performance-sensitive **and** more common than what I'm giving it credit for below, then it would be useful if you could provide more context about what you're doing and why you think that GeoJSON is **prohibitively** inefficient for your use case.

---

**In my personal opinion**, I do not believe that there are enough real-world use cases where the GeoJSON spec for `Point`, `LineString`, `Polygon`, `MultiPoint`, `MultiLineString`, or `MultiPolygon` types is prohibitively expensive, relative to viable **general-purpose** non-standard alternatives, to justify us maintaining support for those alternatives.  Especially for web applications that are already using (or could be easily convinced to start using) general-purpose stream compression.

The inefficiencies of conforming to the GeoJSON spec, compared to viable **general-purpose** non-conforming alternatives (even granting that you know the type of the outermost object), are on the order of a few dozen bytes per geometry object, uncompressed (more, perhaps, if you **really** care about heterogeneous `GeometryCollection` objects).  In my experience, it is **rarely, if ever,** worth investing the time and effort to trim such a low amount of bytes off of a stream.  More likely, either:

- The payload is already small enough that it doesn't matter how much smaller you can make it, because the entire operation is already dominated by latency, not bandwidth; or
- The payload is so large that the potential savings would not make a meaningful enough impact

Complicating things further, spatial data tends to be inherently expensive enough to work with that whatever you're actually **doing** on either end of the pipe is likely to dwarf any potential savings from using a slightly more compact format.

**Comment by verdie-g** [comment]
I agree that the performance argument is not a applicable here. By "compact object" I meant simpler and consistent object. What bothers me the most is what I explained in my first comment, that is a multipoint is not an array of point and that accessing the x ordinate of a point is verbose `myPoint.coordinates[0]`. But as you said, these incovenience are probably not worth investing time on it. I think I will roll with @types/geojson. Thank you very much for your answers.

**Comment by DGuidi** [comment]
> Is Topojson more compact? Looking quickly at https://github.com/topojson/topojson-specification#11-examples it seems like it's not the case

[TopoJSON is substantially more compact than GeoJSON, frequently offering a reduction of 80% or more](https://github.com/topojson/topojson), but this applies as example to large set of geometries polygons/linestring, not points or single features.
